/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertStreamMode: typeof import('./src/components/ai/AlertStreamMode.vue')['default']
    AnalysisCard: typeof import('./src/components/ticket/AnalysisCard.vue')['default']
    AnalyticsMode: typeof import('./src/components/ai/AnalyticsMode.vue')['default']
    ApiErrorState: typeof import('./src/components/common/ApiErrorState.vue')['default']
    AppBreadcrumb: typeof import('./src/components/common/AppBreadcrumb.vue')['default']
    AppEmpty: typeof import('./src/components/common/AppEmpty.vue')['default']
    AppErrorBoundary: typeof import('./src/components/common/AppErrorBoundary.vue')['default']
    AppNavbar: typeof import('./src/components/common/AppNavbar.vue')['default']
    AppSkeleton: typeof import('./src/components/common/AppSkeleton.vue')['default']
    AvatarFallback: typeof import('./src/components/common/AvatarFallback.vue')['default']
    ChatMode: typeof import('./src/components/ai/ChatMode.vue')['default']
    CollapseToggle: typeof import('./src/components/common/CollapseToggle.vue')['default']
    CollapsibleCard: typeof import('./src/components/common/CollapsibleCard.vue')['default']
    CollapsiblePanel: typeof import('./src/components/common/CollapsiblePanel.vue')['default']
    ComingSoonPanel: typeof import('./src/components/common/ComingSoonPanel.vue')['default']
    DataStateBoundary: typeof import('./src/components/common/DataStateBoundary.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HotkeysDialog: typeof import('./src/components/common/HotkeysDialog.vue')['default']
    KnowledgeRichEditor: typeof import('./src/components/knowledge/KnowledgeRichEditor.vue')['default']
    KnowledgeSinkDrawer: typeof import('./src/components/ticket/KnowledgeSinkDrawer.vue')['default']
    KnowledgeTreeSidebar: typeof import('./src/components/knowledge/KnowledgeTreeSidebar.vue')['default']
    NetworkBanner: typeof import('./src/components/common/NetworkBanner.vue')['default']
    PageLoading: typeof import('./src/components/common/PageLoading.vue')['default']
    PanelErrorBoundary: typeof import('./src/components/common/PanelErrorBoundary.vue')['default']
    PostmortemDrawer: typeof import('./src/components/ticket/PostmortemDrawer.vue')['default']
    ProfileDialog: typeof import('./src/components/common/ProfileDialog.vue')['default']
    RailButton: typeof import('./src/components/common/RailButton.vue')['default']
    RelativeTime: typeof import('./src/components/common/RelativeTime.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafeImage: typeof import('./src/components/common/SafeImage.vue')['default']
    ServerPagination: typeof import('./src/components/common/ServerPagination.vue')['default']
    SettingsDialog: typeof import('./src/components/common/SettingsDialog.vue')['default']
    SkeletonRows: typeof import('./src/components/common/SkeletonRows.vue')['default']
    SlaRiskPanel: typeof import('./src/components/dashboard/SlaRiskPanel.vue')['default']
    SuggestionMode: typeof import('./src/components/ai/SuggestionMode.vue')['default']
    ThemeSwitcher: typeof import('./src/components/common/ThemeSwitcher.vue')['default']
    TicketFormDialog: typeof import('./src/components/ticket/TicketFormDialog.vue')['default']
    TicketInsights: typeof import('./src/components/ticket/TicketInsights.vue')['default']
    TrendChart: typeof import('./src/components/common/TrendChart.vue')['default']
  }
}
