-- ============================================================================
-- 【过渡性兼容桩 · 拟于 S0-1 收尾时删除】
--
-- 真相源已迁至 src/main/resources/db/migration/V1__baseline.sql（Flyway 托管，
-- 见 AGENTS.md §3.5）。本文件存在的唯一原因：
--
--   CI 旧步骤仍执行 `psql -f sql/init.sql`，而当前机器人账号无 workflows 权限，
--   无法修改 .github/workflows/ci.yml。待该步骤连同本桩被移除后，
--   schema 创建才完全交给 Flyway（详见 docs/08-benchmark/100 报告 §收尾挂账）。
--
-- 本桩不含任何 DDL，只是把 psql 引导到真正的基线文件，没有任何第二真相源。
-- FlywayMigrationContractTest 仍保证本目录不出现建表语句。
-- ============================================================================
\ir ../src/main/resources/db/migration/V1__baseline.sql
